sudo: required
services:
    - docker

before_install:
    - docker build -t chrisbabu/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run chrisbabu/react-test npm test -- --coverage

after_success:
    - docker build -t chrisbabu/multi-client ./client
    - docker build -t chrisbabu/multi-nginx ./nginx
    - docker build -t chrisbabu/multi-server ./server
    - docker build -t chrisbabu/multi-worker ./worker
    #Log in to the docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin

    #Take this image and push to docker hub
    - docker push chrisbabu/multi-client
    - docker push chrisbabu/multi-nginx
    - docker push chrisbabu/multi-server
    - docker push chrisbabu/multi-worker